//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activation_keys
    {
        public int key_id { get; set; }
        public int issued_user_id { get; set; }
        public string activation_key { get; set; }
        public string key_series { get; set; }
        public decimal key_value { get; set; }
        public short key_status { get; set; }
        public string remarks { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public int activated_by { get; set; }
        public System.DateTime activated_on { get; set; }
        public System.DateTime activated_till { get; set; }
        public short valid_days { get; set; }
        public short is_activated { get; set; }
    }
}
