//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class college
    {
        public int college_id { get; set; }
        public string college_code { get; set; }
        public string college_name { get; set; }
        public string college_type { get; set; }
        public int affiliated_to { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public int country_id { get; set; }
        public int state_id { get; set; }
        public int city_id { get; set; }
        public short stream_id { get; set; }
        public int pincode { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string email_id { get; set; }
        public string website { get; set; }
        public string contact_name { get; set; }
        public int international_rank { get; set; }
        public int national_rank { get; set; }
        public string accreditation_type { get; set; }
        public string accreditation_value { get; set; }
        public int NAAC { get; set; }
        public short active_status { get; set; }
        public System.DateTime inactive_date { get; set; }
    }
}
