//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int department_id { get; set; }
        public string department_code { get; set; }
        public int college_id { get; set; }
        public int stream { get; set; }
        public string department_name { get; set; }
        public short active_status { get; set; }
        public System.DateTime inactive_date { get; set; }
    }
}
