//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public string event_code { get; set; }
        public string event_name { get; set; }
        public string event_type { get; set; }
        public string description { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime to_date { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public string venue { get; set; }
        public int institute_id { get; set; }
        public string targeted_audience { get; set; }
    }
}
