//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int grade_id { get; set; }
        public int country_id { get; set; }
        public int state_id { get; set; }
        public int city_id { get; set; }
        public int university_id { get; set; }
        public int grade_scale { get; set; }
        public double grade_point { get; set; }
        public string grade1 { get; set; }
        public string marks_from { get; set; }
        public string marks_to { get; set; }
        public string interpretation { get; set; }
        public string @class { get; set; }
        public System.DateTime validate_from_date { get; set; }
        public System.DateTime validate_to_date { get; set; }
        public int active_status { get; set; }
    }
}
