//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int mark_id { get; set; }
        public int member_id { get; set; }
        public int university_id { get; set; }
        public int college_id { get; set; }
        public int department_id { get; set; }
        public decimal year { get; set; }
        public short graduation_id { get; set; }
        public short semester_id { get; set; }
        public int subject_id { get; set; }
        public int course_id { get; set; }
        public short internal_mark { get; set; }
        public short external_mark { get; set; }
        public short actual_mark { get; set; }
        public int isAbsent { get; set; }
        public string result { get; set; }
        public short status { get; set; }
    }
}
