//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int member_id { get; set; }
        public string registration_no { get; set; }
        public string registration_code { get; set; }
        public string member_fname { get; set; }
        public string member_lname { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string permanent_address { get; set; }
        public string communication_address { get; set; }
        public int city_id { get; set; }
        public int state_id { get; set; }
        public string zipcode { get; set; }
        public int country_id { get; set; }
        public string mobile { get; set; }
        public int university_id { get; set; }
        public int college_id { get; set; }
        public decimal batch { get; set; }
        public int referered_by { get; set; }
        public System.DateTime registered_on { get; set; }
    }
}
