//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletter
    {
        public int newsletter_id { get; set; }
        public string newsletter_title { get; set; }
        public string newsletter1 { get; set; }
        public System.DateTime newsletter_date { get; set; }
    }
}
