//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orgnization
    {
        public int org_id { get; set; }
        public int org_type { get; set; }
        public string org_name { get; set; }
        public string org_email { get; set; }
        public string org_phone { get; set; }
        public string org_mobile { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public int city_id { get; set; }
        public int state_id { get; set; }
        public int country_id { get; set; }
        public string org_fax { get; set; }
        public string org_website { get; set; }
    }
}
