//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refered_emails
    {
        public int id { get; set; }
        public int refered_by { get; set; }
        public string refered_to_name { get; set; }
        public string refered_email { get; set; }
        public short status { get; set; }
        public System.DateTime refered_on { get; set; }
    }
}
