//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sslc_12th_settings
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int state_id { get; set; }
        public int board_id { get; set; }
        public int medium_id { get; set; }
        public decimal year_of_pass { get; set; }
        public decimal year_of_complete { get; set; }
        public string school_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public int city_id { get; set; }
        public int country_id { get; set; }
        public int pincode { get; set; }
        public int mobile_no { get; set; }
        public int phone_no { get; set; }
        public string email { get; set; }
        public int setting_for { get; set; }
        public string marks_copy_image { get; set; }
        public short jobalert { get; set; }
    }
}
