//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sslc_12th_marks
    {
        public int mark_id { get; set; }
        public int user_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public short min_pass_mark { get; set; }
        public short max_mark { get; set; }
        public short marks_scored { get; set; }
        public short mark_for { get; set; }
    }
}
