//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_modules
    {
        public int sub_module_id { get; set; }
        public int main_id { get; set; }
        public string sub_module_name { get; set; }
        public string sub_module_code { get; set; }
    }
}
