//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public int subject_id { get; set; }
        public string subject_code { get; set; }
        public string subject_name { get; set; }
        public string subject_category { get; set; }
        public string subject_type { get; set; }
        public int state_id { get; set; }
        public int university_id { get; set; }
        public int college_id { get; set; }
        public byte graduation_id { get; set; }
        public int department_id { get; set; }
        public int course_id { get; set; }
        public byte semester_id { get; set; }
        public System.DateTime syllabus_year_from { get; set; }
        public System.DateTime syllabus_year_to { get; set; }
        public byte internal_mark { get; set; }
        public byte internal_min_pass_mark { get; set; }
        public byte external_mark { get; set; }
        public byte external_min_pass_mark { get; set; }
        public byte subject_min_mark { get; set; }
        public byte subject_max_mark { get; set; }
        public byte subject_max_credits { get; set; }
        public byte active_status { get; set; }
        public System.DateTime inactive_date { get; set; }
    }
}
