//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_mapping_settings
    {
        public int id { get; set; }
        public int state_id { get; set; }
        public int university_id { get; set; }
        public int college_id { get; set; }
        public short graduation_id { get; set; }
        public int department_id { get; set; }
        public int course_id { get; set; }
        public short semester_id { get; set; }
        public short min_sub_to_be_filled { get; set; }
        public short max_sub_to_be_filled { get; set; }
        public short max_sub_to_be_displayed { get; set; }
        public short max_sub_to_be_mapped { get; set; }
        public short max_elective_subject { get; set; }
        public short max_core_subjects { get; set; }
        public short max_allied_subjects { get; set; }
    }
}
