//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class support_complaints
    {
        public int complaint_id { get; set; }
        public int user_id { get; set; }
        public short type_id { get; set; }
        public int support_type_id { get; set; }
        public string ticket_subject { get; set; }
        public string issue_code { get; set; }
        public string issue_description { get; set; }
        public System.DateTime posted_on { get; set; }
        public short status { get; set; }
        public string update_notes { get; set; }
        public System.DateTime last_updated_on { get; set; }
        public string last_updated_by { get; set; }
    }
}
