//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class university
    {
        public int university_id { get; set; }
        public string university_code { get; set; }
        public int university_type { get; set; }
        public int country_id { get; set; }
        public int state_id { get; set; }
        public int city_id { get; set; }
        public string university_name { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string pincode { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string email_id { get; set; }
        public string contact_name { get; set; }
        public int international_rank { get; set; }
        public int national_rank { get; set; }
        public int accreditation_type { get; set; }
        public string accreditation_value { get; set; }
        public Nullable<int> NAAC { get; set; }
        public byte active_status { get; set; }
        public System.DateTime inactive_date { get; set; }
    }
}
