//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_activity_log
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_type { get; set; }
        public string action_description { get; set; }
        public string module { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
