//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string name { get; set; }
        public string lname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public int city_id { get; set; }
        public int state_id { get; set; }
        public int country_id { get; set; }
        public int pincode { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public int org_type { get; set; }
        public int org_id { get; set; }
        public short active_status { get; set; }
        public System.DateTime active_from { get; set; }
        public System.DateTime active_to { get; set; }
        public System.DateTime inactive_from { get; set; }
        public short lock_account { get; set; }
    }
}
