//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_members
    {
        public int user_id { get; set; }
        public int member_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public short status { get; set; }
        public short email_verification { get; set; }
        public string activation_key { get; set; }
        public System.DateTime activation_date { get; set; }
        public System.DateTime activated_till_date { get; set; }
        public System.DateTime last_login { get; set; }
        public int logged_in_status { get; set; }
        public short user_type { get; set; }
        public short disable_status { get; set; }
    }
}
