//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_roles
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string description { get; set; }
        public System.DateTime created_on { get; set; }
        public short active_status { get; set; }
    }
}
