//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace academica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_mapping
    {
        public int id { get; set; }
        public int college_id { get; set; }
        public string college_code { get; set; }
        public int organization_id { get; set; }
        public int role_id { get; set; }
        public int user_id { get; set; }
    }
}
